MEMORY
{
    RAM (xrw) : ORIGIN = 0x40000000, LENGTH = 2M
    ROM (xrw) : ORIGIN = 0x20000000, LENGTH = 2M
}

REGION_ALIAS("REGION_TEXT", ROM);
REGION_ALIAS("REGION_RODATA", ROM);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);

_hart_stack_size = 1K;
_heap_size = 1M;
