[package]
name = "nr32-sys"
version = "0.1.0"
edition = "2024"
description = "Generic library routines interfacing with nr32-rt"

[dependencies]
array-const-fn-init = "0.1.1"
log = "0.4"
nr32-common = { path = "../nr32-common" }
